name: Continuous Deployment
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy Website 🚀
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Send files to server
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: files.000webhost.com
                  username: shoponline-web
                  password: ${{ secrets.HOST_PASSWORD }}
                  server-dir: public_html/
